name: dart_chromecast
version: 0.3.5
description: Pure dart package to cast videos to your ChromeCast device and control their playback
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  universal_io: ^2.2.2
  protobuf: ^3.1.0
  cli_util: ^0.4.2
  args: ^2.6.0
  xml: ^6.5.0
  logging: ^1.3.0
  multicast_dns: ^0.3.2+7
